torchrun --nproc_per_node 8 \
	-m FlagEmbedding.finetune.reranker.encoder_only.base \
	--model_name_or_path /workspace/FlagEmbedding/examples/finetune/reranker/gte-multilingual-reranker-base \
    --cache_dir ./cache/model \
    --train_data ../example_data/sigrid/training_pairs_data_score_decoded.jsonl \
    --cache_path ./cache/data \
    --train_group_size 8 \
    --query_max_len 512 \
    --passage_max_len 512 \
    --pad_to_multiple_of 8 \
    --knowledge_distillation False \
	--output_dir ./gte-korean-reranker-base-preview-241105-a \
    --overwrite_output_dir \
    --learning_rate 6e-5 \
    --fp16 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --dataloader_drop_last True \
    --warmup_ratio 0.1 \
    --gradient_checkpointing \
    --weight_decay 0.01 \
    --deepspeed /workspace/sigrid/FlagEmbedding/examples/finetune/ds_stage0.json \
    --logging_steps 1 \
    --save_steps 1000 \
    --trust_remote_code true
